env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  max-len: ["error", {"code": 120, "tabWidth": 4, "ignoreUrls": true}]
  require-jsdoc: "off"
  valid-jsdoc: "off"
  new-cap: "warn"
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": "error"
